spring:
  application:
    name: student-management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/student_management_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true